export const landingPage = {
  brand1: require("./brand1.png"),
  brand2: require("./brand2.png"),
  brand3: require("./brand3.png"),
  brand4: require("./brand4.png"),
  brand5: require("./brand5.png"),
  brand6: require("./brand6.png"),
  brand7: require("./brand7.png"),
  banner1: require("./banner1.png"),
  banner2: require("./banner2.png"),
  profile1: require("./profile1.png"),
  profile2: require("./profile2.png"),
  profile3: require("./profile3.png"),
  phone: require("./phone.png"),
  bg1: require("./bg1.png"),
  logo: require("./logo-color.png"),
  logoHeader: require("./logo.png"),
  noBg: require("./noBg.png"),
  bgProject: require("./bgProject.png"),
  handWithPhone: require("./hand-with-phone.png"),
  photoConcept: require("./photo-concept.png"),
  contentCreative: require("./content-creative.png"),
  ava2: require("./ava-2.png"),
  vector: require("./Vector.svg"),
};
